pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'your-linux-command'
                    } else {
                        bat 'your-windows-command'
                    }
                }
            }
        }
    }
}
